import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const newEvents = [
        // Cricket Events (8 total)
        {
            title: 'India vs Australia - 1st Test Match',
            sport: 'Cricket',
            league: 'International Test',
            date: new Date('2024-02-09T09:30:00Z').toISOString(),
            location: 'Melbourne Cricket Ground (MCG), Melbourne, Australia',
            homeTeam: 'Australia',
            awayTeam: 'India',
            score: 'Australia 487 & 234/6d, India 571 & 152/3',
            imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
            description: 'An epic Test match at the iconic MCG. India dominated with a massive first innings total of 571, featuring a magnificent double century from Virat Kohli (214*) and crucial partnerships throughout. Australia fought back valiantly in their second innings, setting a challenging target. India ended day 5 needing just 150 more runs with 7 wickets in hand, showcasing excellent batting depth.',
            createdAt: new Date('2024-01-25T10:00:00Z').toISOString(),
        },
        {
            title: 'England vs Pakistan - 3rd ODI',
            sport: 'Cricket',
            league: 'ODI International',
            date: new Date('2024-03-15T14:00:00Z').toISOString(),
            location: 'Lord\'s Cricket Ground, London, England',
            homeTeam: 'England',
            awayTeam: 'Pakistan',
            score: 'England 267/9, Pakistan 265 all out',
            imageUrl: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800',
            description: 'A nail-biting finish at the Home of Cricket! England defended 267 in a thrilling encounter, winning by just 2 runs. Pakistan needed 12 runs off the final over but excellent death bowling from Mark Wood (3/45) sealed the victory. Jos Buttler\'s aggressive 87 and a crucial 92-run partnership between Joe Root and Ben Stokes set up England\'s total.',
            createdAt: new Date('2024-02-01T10:00:00Z').toISOString(),
        },
        {
            title: 'IPL 2024: Mumbai Indians vs Chennai Super Kings',
            sport: 'Cricket',
            league: 'IPL',
            date: new Date('2024-04-06T19:30:00Z').toISOString(),
            location: 'Wankhede Stadium, Mumbai, India',
            homeTeam: 'Mumbai Indians',
            awayTeam: 'Chennai Super Kings',
            score: 'Mumbai Indians 185/6, Chennai Super Kings 178/8',
            imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
            description: 'A classic IPL rivalry delivers again! Mumbai Indians defended 185 in a tense finish at their home ground. Hardik Pandya\'s explosive 67 off 31 balls powered MI to a competitive total. CSK looked on track at 145/3 in the 16th over, but a brilliant spell from Jasprit Bumrah (3/28) including two wickets in the 18th over turned the match. MS Dhoni\'s late cameo (31* off 17) wasn\'t enough.',
            createdAt: new Date('2024-02-10T10:00:00Z').toISOString(),
        },
        {
            title: 'South Africa vs New Zealand - T20 International',
            sport: 'Cricket',
            league: 'T20 International',
            date: new Date('2024-01-28T17:00:00Z').toISOString(),
            location: 'Adelaide Oval, Adelaide, Australia',
            homeTeam: 'South Africa',
            awayTeam: 'New Zealand',
            score: 'South Africa 189/4, New Zealand 192/3',
            imageUrl: 'https://images.unsplash.com/photo-1593766787879-e8c78e09cec8?w=800',
            description: 'New Zealand chased down 190 with remarkable ease at Adelaide Oval. Devon Conway\'s masterful 82* off 53 balls and a blistering opening partnership of 98 runs set the platform. Kane Williamson provided perfect support with an unbeaten 45. Earlier, Aiden Markram\'s 71 off 42 powered South Africa to a competitive total, but the Kiwi batting lineup proved too strong.',
            createdAt: new Date('2024-01-15T10:00:00Z').toISOString(),
        },
        {
            title: 'BBL Final: Sydney Sixers vs Perth Scorchers',
            sport: 'Cricket',
            league: 'BBL',
            date: new Date('2024-02-24T19:15:00Z').toISOString(),
            location: 'Sydney Cricket Ground, Sydney, Australia',
            homeTeam: 'Sydney Sixers',
            awayTeam: 'Perth Scorchers',
            score: 'Sydney Sixers 167/7, Perth Scorchers 171/5',
            imageUrl: 'https://images.unsplash.com/photo-1596230644779-f3e6c6cae7a1?w=800',
            description: 'Perth Scorchers clinched the BBL title with a thrilling 5-wicket victory at the SCG. Chasing 168, Mitchell Marsh\'s powerful 61 off 36 balls anchored the chase. The match went down to the final over, with Aaron Hardie hitting the winning runs with 3 balls to spare. Earlier, Moises Henriques\' 54 had given Sixers hope, but the Scorchers\' experience proved decisive.',
            createdAt: new Date('2024-02-05T10:00:00Z').toISOString(),
        },
        {
            title: 'PSL 2024: Karachi Kings vs Lahore Qalandars',
            sport: 'Cricket',
            league: 'PSL',
            date: new Date('2024-03-10T19:00:00Z').toISOString(),
            location: 'National Stadium, Karachi, Pakistan',
            homeTeam: 'Karachi Kings',
            awayTeam: 'Lahore Qalandars',
            score: 'Karachi Kings 178/6, Lahore Qalandars 182/4',
            imageUrl: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800',
            description: 'Lahore Qalandars secured a commanding 6-wicket victory in this PSL clash. Fakhar Zaman\'s explosive 89 off 51 balls, including 7 sixes, demolished the Karachi bowling attack. Shaheen Afridi earlier took 2 crucial wickets to restrict Karachi to 178. Babar Azam\'s elegant 62 for Karachi wasn\'t enough as Lahore chased down the target with 11 balls remaining.',
            createdAt: new Date('2024-02-15T10:00:00Z').toISOString(),
        },
        {
            title: 'Australia vs England - 2nd T20I',
            sport: 'Cricket',
            league: 'T20 International',
            date: new Date('2024-04-20T18:30:00Z').toISOString(),
            location: 'Eden Gardens, Kolkata, India',
            homeTeam: 'Australia',
            awayTeam: 'England',
            score: '',
            imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
            description: 'The second T20I of this highly anticipated series comes to the historic Eden Gardens. After a thrilling first match, both teams will be looking to assert dominance. Australia\'s pace attack led by Mitchell Starc and Pat Cummins will face England\'s explosive batting lineup featuring Jos Buttler and Ben Stokes. The Eden Gardens crowd is expected to create an electric atmosphere for this crucial encounter.',
            createdAt: new Date('2024-02-20T10:00:00Z').toISOString(),
        },
        {
            title: 'India vs South Africa - ODI Series Decider',
            sport: 'Cricket',
            league: 'ODI International',
            date: new Date('2024-05-05T14:30:00Z').toISOString(),
            location: 'Wankhede Stadium, Mumbai, India',
            homeTeam: 'India',
            awayTeam: 'South Africa',
            score: '',
            imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
            description: 'The series decider promises to be a blockbuster at Mumbai\'s iconic Wankhede Stadium. With the series locked at 2-2, both teams will give their all in this crucial final ODI. India\'s spin trio of Kuldeep Yadav, Ravindra Jadeja, and Axar Patel will be key on a turning Wankhede pitch. South Africa\'s batting lineup led by Quinton de Kock and Rassie van der Dussen will need to fire to challenge India in front of their home crowd.',
            createdAt: new Date('2024-02-22T10:00:00Z').toISOString(),
        },

        // F1 Events (8 total)
        {
            title: 'Monaco Grand Prix 2024',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-05-26T15:00:00Z').toISOString(),
            location: 'Circuit de Monaco, Monte Carlo, Monaco',
            homeTeam: 'Charles Leclerc (Ferrari)',
            awayTeam: 'Max Verstappen (Red Bull)',
            score: '',
            imageUrl: 'https://images.unsplash.com/photo-1532906619279-a4b7267faa66?w=800',
            description: 'The jewel in the F1 calendar returns to the streets of Monte Carlo. Charles Leclerc will be desperate to break his Monaco curse and secure his first home victory. The narrow, twisting street circuit provides minimal overtaking opportunities, making qualifying absolutely crucial. Red Bull\'s Max Verstappen leads the championship and will be looking to extend his advantage. Strategy and tire management will be key on this historic circuit.',
            createdAt: new Date('2024-02-01T10:00:00Z').toISOString(),
        },
        {
            title: 'Australian Grand Prix 2024',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-03-24T05:00:00Z').toISOString(),
            location: 'Albert Park Circuit, Melbourne, Australia',
            homeTeam: 'Max Verstappen (Red Bull)',
            awayTeam: 'Lewis Hamilton (Mercedes)',
            score: '1st: 1:28:56.431, 2nd: +3.164s',
            imageUrl: 'https://images.unsplash.com/photo-1541443131876-44b03de101c5?w=800',
            description: 'Max Verstappen dominated the season opener in Melbourne with a lights-to-flag victory. Starting from pole position, the Dutch driver controlled the race perfectly, managing his tires and pulling away from the field. Lewis Hamilton delivered a strong performance to finish second, showcasing Mercedes\' improved pace. A late safety car bunched up the field, but Verstappen nailed the restart. Lando Norris completed the podium with an impressive drive for McLaren.',
            createdAt: new Date('2024-01-20T10:00:00Z').toISOString(),
        },
        {
            title: 'British Grand Prix at Silverstone',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-04-07T14:00:00Z').toISOString(),
            location: 'Silverstone Circuit, Northamptonshire, England',
            homeTeam: 'Lewis Hamilton (Mercedes)',
            awayTeam: 'Lando Norris (McLaren)',
            score: '1st: 1:25:42.987, 2nd: +8.536s',
            imageUrl: 'https://images.unsplash.com/photo-1595475207225-428b62bda831?w=800',
            description: 'Lewis Hamilton delivered a masterclass at his home race, securing a record-extending 9th British GP victory. The seven-time champion executed a brilliant one-stop strategy on a drying track after early rain showers. Starting from P5, Hamilton\'s aggressive overtakes through Copse and Stowe thrilled the packed Silverstone crowd. Lando Norris provided fierce competition, leading for 18 laps before Hamilton\'s superior tire management paid off. George Russell completed an all-British podium in P3.',
            createdAt: new Date('2024-01-28T10:00:00Z').toISOString(),
        },
        {
            title: 'Italian Grand Prix at Monza',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-06-02T15:00:00Z').toISOString(),
            location: 'Autodromo Nazionale di Monza, Monza, Italy',
            homeTeam: 'Charles Leclerc (Ferrari)',
            awayTeam: 'Max Verstappen (Red Bull)',
            score: '',
            imageUrl: 'https://images.unsplash.com/photo-1566574116428-b3c0e03e5d5e?w=800',
            description: 'Ferrari returns to their beloved Temple of Speed with hopes of a home victory. The high-speed Monza circuit with its long straights and chicanes will test the cars\' top speed and aerodynamic efficiency. Charles Leclerc and Carlos Sainz will have the passionate Tifosi behind them, creating an atmosphere unlike any other. Red Bull\'s Max Verstappen remains the favorite, but Ferrari\'s recent upgrades could shake up the order. The race often features dramatic slipstreaming battles and brave overtakes.',
            createdAt: new Date('2024-02-05T10:00:00Z').toISOString(),
        },
        {
            title: 'Belgian Grand Prix at Spa-Francorchamps',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-03-31T14:00:00Z').toISOString(),
            location: 'Circuit de Spa-Francorchamps, Stavelot, Belgium',
            homeTeam: 'Max Verstappen (Red Bull)',
            awayTeam: 'Sergio Perez (Red Bull)',
            score: '1st: 1:24:30.552, 2nd: +22.305s',
            imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
            description: 'Red Bull Racing secured a dominant 1-2 finish at the legendary Spa-Francorchamps circuit. Max Verstappen showcased brilliant racecraft through the challenging Eau Rouge and Raidillon complex, pulling away from the field with fastest lap after fastest lap. The race featured dramatic weather changes, with teams gambling on tire strategies. Sergio Perez held off Fernando Alonso\'s charging Aston Martin to secure second place. A first-lap incident at La Source brought out the safety car, bunching the field.',
            createdAt: new Date('2024-02-08T10:00:00Z').toISOString(),
        },
        {
            title: 'Japanese Grand Prix at Suzuka',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-04-14T06:00:00Z').toISOString(),
            location: 'Suzuka International Racing Course, Suzuka, Japan',
            homeTeam: 'Max Verstappen (Red Bull)',
            awayTeam: 'Lando Norris (McLaren)',
            score: '1st: 1:31:15.946, 2nd: +19.872s',
            imageUrl: 'https://images.unsplash.com/photo-1547038577-4f0e4c669352?w=800',
            description: 'Another commanding victory for Max Verstappen at the iconic figure-eight Suzuka circuit. The Red Bull driver was untouchable throughout the weekend, taking pole position and leading every lap of the race. Lando Norris delivered an impressive performance to finish second, showing McLaren\'s continued development progress. The demanding 130R corner and Spoon Curve provided spectacular racing. Ferrari\'s Charles Leclerc completed the podium after an intense battle with George Russell that went down to the final lap.',
            createdAt: new Date('2024-02-12T10:00:00Z').toISOString(),
        },
        {
            title: 'Singapore Grand Prix Night Race',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-05-18T13:00:00Z').toISOString(),
            location: 'Marina Bay Street Circuit, Singapore',
            homeTeam: 'Charles Leclerc (Ferrari)',
            awayTeam: 'Lewis Hamilton (Mercedes)',
            score: '',
            imageUrl: 'https://images.unsplash.com/photo-1524498250077-390f9e378fc0?w=800',
            description: 'F1\'s premier night race returns to the stunning Marina Bay street circuit. The challenging 23-turn layout under the floodlights creates a unique spectacle. High humidity and temperatures make this one of the most physically demanding races of the season. Ferrari has shown strong pace on street circuits this year, making Charles Leclerc a serious contender. The narrow track and barrier-lined corners mean one mistake can end your race. Expect strategy surprises and potential safety car periods in this grueling two-hour battle.',
            createdAt: new Date('2024-02-16T10:00:00Z').toISOString(),
        },
        {
            title: 'Abu Dhabi Grand Prix Season Finale',
            sport: 'F1',
            league: 'Formula 1',
            date: new Date('2024-06-09T14:00:00Z').toISOString(),
            location: 'Yas Marina Circuit, Abu Dhabi, UAE',
            homeTeam: 'Max Verstappen (Red Bull)',
            awayTeam: 'Fernando Alonso (Aston Martin)',
            score: '',
            imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800',
            description: 'The season finale under the lights at Yas Marina promises high drama as championships could be decided. The venue of many historic title showdowns, this year could see another thrilling conclusion. Max Verstappen aims to seal another world championship, but rivals are closing the gap. The recently modified circuit layout has improved racing with better overtaking zones. As the sun sets and the lights come on, teams will push their cars and strategies to the limit for one final glory run of the season.',
            createdAt: new Date('2024-02-18T10:00:00Z').toISOString(),
        },
    ];

    await db.insert(events).values(newEvents);
    
    console.log('✅ Events seeder completed successfully - Added 16 new sports events (8 Cricket + 8 F1)');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});