import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const sampleEvents = [
        {
            title: 'Lakers vs Celtics',
            sport: 'Basketball',
            league: 'NBA',
            date: new Date('2024-03-15T19:30:00').toISOString(),
            location: 'Staples Center, Los Angeles',
            home_team: 'Los Angeles Lakers',
            away_team: 'Boston Celtics',
            score: '108-102',
            image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc',
            description: 'Epic showdown between two legendary franchises in a thrilling overtime finish.',
            created_at: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Chiefs vs Bills',
            sport: 'Football',
            league: 'NFL',
            date: new Date('2024-02-20T18:00:00').toISOString(),
            location: 'Arrowhead Stadium, Kansas City',
            home_team: 'Kansas City Chiefs',
            away_team: 'Buffalo Bills',
            score: '27-24',
            image_url: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2',
            description: 'Playoff thriller with the Chiefs securing a last-minute victory.',
            created_at: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Cowboys vs Eagles',
            sport: 'Football',
            league: 'NFL',
            date: new Date('2024-03-10T20:15:00').toISOString(),
            location: 'AT&T Stadium, Dallas',
            home_team: 'Dallas Cowboys',
            away_team: 'Philadelphia Eagles',
            score: '31-28',
            image_url: 'https://images.unsplash.com/photo-1520095972714-909e91b038e5',
            description: 'NFC East rivalry game with playoff implications on the line.',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Man City vs Arsenal',
            sport: 'Soccer',
            league: 'Premier League',
            date: new Date('2024-03-25T15:00:00').toISOString(),
            location: 'Etihad Stadium, Manchester',
            home_team: 'Manchester City',
            away_team: 'Arsenal',
            score: '2-1',
            image_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018',
            description: 'Title race decider with City taking control at home.',
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Liverpool vs Chelsea',
            sport: 'Soccer',
            league: 'Premier League',
            date: new Date('2024-04-01T17:30:00').toISOString(),
            location: 'Anfield, Liverpool',
            home_team: 'Liverpool',
            away_team: 'Chelsea',
            score: '3-2',
            image_url: 'https://images.unsplash.com/photo-1551958219-acbc608c6377',
            description: 'Five-goal thriller at Anfield with end-to-end action.',
            created_at: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Yankees vs Dodgers - World Series Game 1',
            sport: 'Baseball',
            league: 'MLB',
            date: new Date('2024-10-25T20:00:00').toISOString(),
            location: 'Yankee Stadium, New York',
            home_team: 'New York Yankees',
            away_team: 'Los Angeles Dodgers',
            score: '5-3',
            image_url: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390',
            description: 'World Series opener with the Yankees taking Game 1 at home.',
            created_at: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Yankees vs Dodgers - World Series Game 2',
            sport: 'Baseball',
            league: 'MLB',
            date: new Date('2024-10-26T20:00:00').toISOString(),
            location: 'Yankee Stadium, New York',
            home_team: 'New York Yankees',
            away_team: 'Los Angeles Dodgers',
            score: '2-4',
            image_url: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff',
            description: 'Dodgers even the series with strong pitching performance.',
            created_at: new Date('2024-01-24').toISOString(),
        },
        {
            title: 'Bruins vs Maple Leafs',
            sport: 'Hockey',
            league: 'NHL',
            date: new Date('2024-03-18T19:00:00').toISOString(),
            location: 'TD Garden, Boston',
            home_team: 'Boston Bruins',
            away_team: 'Toronto Maple Leafs',
            score: '4-3',
            image_url: 'https://images.unsplash.com/photo-1515703407324-5f753afd8be8',
            description: 'Original Six matchup with overtime drama.',
            created_at: new Date('2024-01-26').toISOString(),
        },
        {
            title: 'Real Madrid vs Bayern Munich',
            sport: 'Soccer',
            league: 'UEFA Champions League',
            date: new Date('2024-04-10T21:00:00').toISOString(),
            location: 'Santiago Bernabéu, Madrid',
            home_team: 'Real Madrid',
            away_team: 'Bayern Munich',
            score: '3-2',
            image_url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20',
            description: 'Champions League semi-final first leg classic.',
            created_at: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Warriors vs Suns',
            sport: 'Basketball',
            league: 'NBA',
            date: new Date('2024-03-28T22:00:00').toISOString(),
            location: 'Chase Center, San Francisco',
            home_team: 'Golden State Warriors',
            away_team: 'Phoenix Suns',
            score: '115-110',
            image_url: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a',
            description: 'Western Conference showdown featuring elite three-point shooting.',
            created_at: new Date('2024-01-30').toISOString(),
        },
        {
            title: 'Red Sox vs Astros',
            sport: 'Baseball',
            league: 'MLB',
            date: new Date('2024-05-15T19:10:00').toISOString(),
            location: 'Fenway Park, Boston',
            home_team: 'Boston Red Sox',
            away_team: 'Houston Astros',
            score: '7-5',
            image_url: 'https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4',
            description: 'High-scoring affair at historic Fenway Park.',
            created_at: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'Packers vs 49ers',
            sport: 'Football',
            league: 'NFL',
            date: new Date('2024-02-05T16:30:00').toISOString(),
            location: 'Lambeau Field, Green Bay',
            home_team: 'Green Bay Packers',
            away_team: 'San Francisco 49ers',
            score: '21-24',
            image_url: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6',
            description: 'Frozen tundra playoff battle with 49ers advancing.',
            created_at: new Date('2024-02-03').toISOString(),
        },
        {
            title: 'Barcelona vs PSG',
            sport: 'Soccer',
            league: 'UEFA Champions League',
            date: new Date('2024-04-15T21:00:00').toISOString(),
            location: 'Camp Nou, Barcelona',
            home_team: 'Barcelona',
            away_team: 'Paris Saint-Germain',
            score: '4-1',
            image_url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d',
            description: 'Dominant Barcelona performance in Champions League knockout stage.',
            created_at: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Rangers vs Lightning',
            sport: 'Hockey',
            league: 'NHL',
            date: new Date('2024-03-22T19:30:00').toISOString(),
            location: 'Madison Square Garden, New York',
            home_team: 'New York Rangers',
            away_team: 'Tampa Bay Lightning',
            score: '3-2',
            image_url: 'https://images.unsplash.com/photo-1529469599898-90dcb15afbf7',
            description: 'Intense playoff rematch at the Garden.',
            created_at: new Date('2024-02-07').toISOString(),
        },
        {
            title: 'Bucks vs Nets',
            sport: 'Basketball',
            league: 'NBA',
            date: new Date('2024-04-05T19:30:00').toISOString(),
            location: 'Fiserv Forum, Milwaukee',
            home_team: 'Milwaukee Bucks',
            away_team: 'Brooklyn Nets',
            score: '122-118',
            image_url: 'https://images.unsplash.com/photo-1519861531473-9200262188bf',
            description: 'Eastern Conference rivalry with superstar performances.',
            created_at: new Date('2024-02-09').toISOString(),
        },
        {
            title: 'Manchester United vs Tottenham',
            sport: 'Soccer',
            league: 'Premier League',
            date: new Date('2024-04-20T12:30:00').toISOString(),
            location: 'Old Trafford, Manchester',
            home_team: 'Manchester United',
            away_team: 'Tottenham Hotspur',
            score: '2-2',
            image_url: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972',
            description: 'Six-pointer for European qualification ends in dramatic draw.',
            created_at: new Date('2024-02-11').toISOString(),
        },
        {
            title: 'Cubs vs Cardinals',
            sport: 'Baseball',
            league: 'MLB',
            date: new Date('2024-06-10T13:20:00').toISOString(),
            location: 'Wrigley Field, Chicago',
            home_team: 'Chicago Cubs',
            away_team: 'St. Louis Cardinals',
            score: '6-4',
            image_url: 'https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4',
            description: 'Historic NL Central rivalry game on a sunny afternoon.',
            created_at: new Date('2024-02-13').toISOString(),
        },
        {
            title: 'Ravens vs Steelers',
            sport: 'Football',
            league: 'NFL',
            date: new Date('2024-01-28T13:00:00').toISOString(),
            location: 'M&T Bank Stadium, Baltimore',
            home_team: 'Baltimore Ravens',
            away_team: 'Pittsburgh Steelers',
            score: '17-10',
            image_url: 'https://images.unsplash.com/photo-1577223625816-7546f9e49521',
            description: 'Hard-hitting AFC North defensive battle.',
            created_at: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Canadiens vs Oilers',
            sport: 'Hockey',
            league: 'NHL',
            date: new Date('2024-03-30T19:00:00').toISOString(),
            location: 'Bell Centre, Montreal',
            home_team: 'Montreal Canadiens',
            away_team: 'Edmonton Oilers',
            score: '5-4',
            image_url: 'https://images.unsplash.com/photo-1515703407324-5f753afd8be8',
            description: 'High-scoring affair featuring Connor McDavid\'s hat trick.',
            created_at: new Date('2024-02-17').toISOString(),
        },
        {
            title: 'Heat vs Celtics',
            sport: 'Basketball',
            league: 'NBA',
            date: new Date('2024-04-12T20:00:00').toISOString(),
            location: 'TD Garden, Boston',
            home_team: 'Boston Celtics',
            away_team: 'Miami Heat',
            score: '98-95',
            image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc',
            description: 'Eastern Conference playoff preview with clutch performances.',
            created_at: new Date('2024-02-19').toISOString(),
        },
    ];

    await db.insert(events).values(sampleEvents);
    
    console.log('✅ Events seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});