import { db } from '@/db';
import { playerStats } from '@/db/schema';

async function main() {
    const samplePlayerStats = [
        // Cricket - Scorecard 1 (India vs Australia)
        {
            scorecardId: 1,
            playerName: 'Virat Kohli',
            teamName: 'India',
            position: 3,
            stats: {
                role: 'Batsman',
                runsScored: 87,
                ballsFaced: 94,
                fours: 8,
                sixes: 2,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Rohit Sharma',
            teamName: 'India',
            position: 1,
            stats: {
                role: 'Batsman',
                runsScored: 52,
                ballsFaced: 67,
                fours: 6,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 2
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Shubman Gill',
            teamName: 'India',
            position: 2,
            stats: {
                role: 'Batsman',
                runsScored: 34,
                ballsFaced: 41,
                fours: 4,
                sixes: 0,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'KL Rahul',
            teamName: 'India',
            position: 4,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 45,
                ballsFaced: 58,
                fours: 5,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 3
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Hardik Pandya',
            teamName: 'India',
            position: 5,
            stats: {
                role: 'All-rounder',
                runsScored: 28,
                ballsFaced: 22,
                fours: 2,
                sixes: 2,
                wicketsTaken: 2,
                oversBowled: 8,
                runsGiven: 42,
                economy: 5.25,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Ravindra Jadeja',
            teamName: 'India',
            position: 6,
            stats: {
                role: 'All-rounder',
                runsScored: 18,
                ballsFaced: 24,
                fours: 1,
                sixes: 0,
                wicketsTaken: 3,
                oversBowled: 10,
                runsGiven: 38,
                economy: 3.8,
                catches: 2
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Jasprit Bumrah',
            teamName: 'India',
            position: 7,
            stats: {
                role: 'Bowler',
                runsScored: 4,
                ballsFaced: 7,
                fours: 0,
                sixes: 0,
                wicketsTaken: 4,
                oversBowled: 10,
                runsGiven: 35,
                economy: 3.5,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Mohammed Shami',
            teamName: 'India',
            position: 8,
            stats: {
                role: 'Bowler',
                runsScored: 8,
                ballsFaced: 12,
                fours: 1,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 9,
                runsGiven: 44,
                economy: 4.89,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Kuldeep Yadav',
            teamName: 'India',
            position: 9,
            stats: {
                role: 'Bowler',
                runsScored: 2,
                ballsFaced: 5,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 10,
                runsGiven: 52,
                economy: 5.2,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Shardul Thakur',
            teamName: 'India',
            position: 10,
            stats: {
                role: 'Bowler',
                runsScored: 12,
                ballsFaced: 14,
                fours: 1,
                sixes: 1,
                wicketsTaken: 1,
                oversBowled: 7,
                runsGiven: 39,
                economy: 5.57,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Mohammed Siraj',
            teamName: 'India',
            position: 11,
            stats: {
                role: 'Bowler',
                runsScored: 0,
                ballsFaced: 2,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 8.5,
                runsGiven: 48,
                economy: 5.45,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Steve Smith',
            teamName: 'Australia',
            position: 1,
            stats: {
                role: 'Batsman',
                runsScored: 76,
                ballsFaced: 88,
                fours: 7,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'David Warner',
            teamName: 'Australia',
            position: 2,
            stats: {
                role: 'Batsman',
                runsScored: 43,
                ballsFaced: 52,
                fours: 5,
                sixes: 0,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Marnus Labuschagne',
            teamName: 'Australia',
            position: 3,
            stats: {
                role: 'Batsman',
                runsScored: 29,
                ballsFaced: 38,
                fours: 3,
                sixes: 0,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 2
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Glenn Maxwell',
            teamName: 'Australia',
            position: 4,
            stats: {
                role: 'All-rounder',
                runsScored: 38,
                ballsFaced: 31,
                fours: 3,
                sixes: 2,
                wicketsTaken: 1,
                oversBowled: 6,
                runsGiven: 34,
                economy: 5.67,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Alex Carey',
            teamName: 'Australia',
            position: 5,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 31,
                ballsFaced: 39,
                fours: 3,
                sixes: 0,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 2
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Mitchell Marsh',
            teamName: 'Australia',
            position: 6,
            stats: {
                role: 'All-rounder',
                runsScored: 24,
                ballsFaced: 28,
                fours: 2,
                sixes: 1,
                wicketsTaken: 1,
                oversBowled: 7,
                runsGiven: 41,
                economy: 5.86,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Pat Cummins',
            teamName: 'Australia',
            position: 7,
            stats: {
                role: 'Bowler',
                runsScored: 15,
                ballsFaced: 18,
                fours: 1,
                sixes: 0,
                wicketsTaken: 3,
                oversBowled: 10,
                runsGiven: 47,
                economy: 4.7,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Mitchell Starc',
            teamName: 'Australia',
            position: 8,
            stats: {
                role: 'Bowler',
                runsScored: 8,
                ballsFaced: 11,
                fours: 0,
                sixes: 1,
                wicketsTaken: 2,
                oversBowled: 9,
                runsGiven: 51,
                economy: 5.67,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Josh Hazlewood',
            teamName: 'Australia',
            position: 9,
            stats: {
                role: 'Bowler',
                runsScored: 3,
                ballsFaced: 7,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 43,
                economy: 4.3,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Adam Zampa',
            teamName: 'Australia',
            position: 10,
            stats: {
                role: 'Bowler',
                runsScored: 1,
                ballsFaced: 3,
                fours: 0,
                sixes: 0,
                wicketsTaken: 3,
                oversBowled: 10,
                runsGiven: 45,
                economy: 4.5,
                catches: 1
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            scorecardId: 1,
            playerName: 'Nathan Lyon',
            teamName: 'Australia',
            position: 11,
            stats: {
                role: 'Bowler',
                runsScored: 0,
                ballsFaced: 1,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 8,
                runsGiven: 49,
                economy: 6.13,
                catches: 0
            },
            createdAt: new Date('2024-01-15').toISOString(),
        },

        // Cricket - Scorecard 2 (England vs Pakistan)
        {
            scorecardId: 2,
            playerName: 'Jos Buttler',
            teamName: 'England',
            position: 1,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 94,
                ballsFaced: 83,
                fours: 10,
                sixes: 3,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 2
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Jonny Bairstow',
            teamName: 'England',
            position: 2,
            stats: {
                role: 'Batsman',
                runsScored: 67,
                ballsFaced: 71,
                fours: 7,
                sixes: 2,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Joe Root',
            teamName: 'England',
            position: 3,
            stats: {
                role: 'Batsman',
                runsScored: 58,
                ballsFaced: 64,
                fours: 6,
                sixes: 0,
                wicketsTaken: 0,
                oversBowled: 2,
                runsGiven: 18,
                economy: 9.0,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Ben Stokes',
            teamName: 'England',
            position: 4,
            stats: {
                role: 'All-rounder',
                runsScored: 41,
                ballsFaced: 38,
                fours: 4,
                sixes: 1,
                wicketsTaken: 2,
                oversBowled: 8,
                runsGiven: 46,
                economy: 5.75,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Harry Brook',
            teamName: 'England',
            position: 5,
            stats: {
                role: 'Batsman',
                runsScored: 29,
                ballsFaced: 27,
                fours: 3,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Moeen Ali',
            teamName: 'England',
            position: 6,
            stats: {
                role: 'All-rounder',
                runsScored: 22,
                ballsFaced: 19,
                fours: 2,
                sixes: 1,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 48,
                economy: 4.8,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Sam Curran',
            teamName: 'England',
            position: 7,
            stats: {
                role: 'All-rounder',
                runsScored: 18,
                ballsFaced: 14,
                fours: 1,
                sixes: 1,
                wicketsTaken: 3,
                oversBowled: 9,
                runsGiven: 42,
                economy: 4.67,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Chris Woakes',
            teamName: 'England',
            position: 8,
            stats: {
                role: 'Bowler',
                runsScored: 11,
                ballsFaced: 13,
                fours: 1,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 10,
                runsGiven: 54,
                economy: 5.4,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Adil Rashid',
            teamName: 'England',
            position: 9,
            stats: {
                role: 'Bowler',
                runsScored: 5,
                ballsFaced: 8,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 49,
                economy: 4.9,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Mark Wood',
            teamName: 'England',
            position: 10,
            stats: {
                role: 'Bowler',
                runsScored: 3,
                ballsFaced: 5,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 8,
                runsGiven: 51,
                economy: 6.38,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Reece Topley',
            teamName: 'England',
            position: 11,
            stats: {
                role: 'Bowler',
                runsScored: 0,
                ballsFaced: 2,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 9,
                runsGiven: 47,
                economy: 5.22,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Babar Azam',
            teamName: 'Pakistan',
            position: 1,
            stats: {
                role: 'Batsman',
                runsScored: 82,
                ballsFaced: 91,
                fours: 8,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Mohammad Rizwan',
            teamName: 'Pakistan',
            position: 2,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 71,
                ballsFaced: 78,
                fours: 7,
                sixes: 2,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 3
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Fakhar Zaman',
            teamName: 'Pakistan',
            position: 3,
            stats: {
                role: 'Batsman',
                runsScored: 38,
                ballsFaced: 42,
                fours: 4,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Iftikhar Ahmed',
            teamName: 'Pakistan',
            position: 4,
            stats: {
                role: 'All-rounder',
                runsScored: 27,
                ballsFaced: 29,
                fours: 2,
                sixes: 1,
                wicketsTaken: 1,
                oversBowled: 5,
                runsGiven: 32,
                economy: 6.4,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Shadab Khan',
            teamName: 'Pakistan',
            position: 5,
            stats: {
                role: 'All-rounder',
                runsScored: 19,
                ballsFaced: 21,
                fours: 1,
                sixes: 1,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 52,
                economy: 5.2,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Mohammad Nawaz',
            teamName: 'Pakistan',
            position: 6,
            stats: {
                role: 'All-rounder',
                runsScored: 14,
                ballsFaced: 16,
                fours: 1,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 8,
                runsGiven: 45,
                economy: 5.63,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Shaheen Afridi',
            teamName: 'Pakistan',
            position: 7,
            stats: {
                role: 'Bowler',
                runsScored: 8,
                ballsFaced: 10,
                fours: 1,
                sixes: 0,
                wicketsTaken: 3,
                oversBowled: 10,
                runsGiven: 48,
                economy: 4.8,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Haris Rauf',
            teamName: 'Pakistan',
            position: 8,
            stats: {
                role: 'Bowler',
                runsScored: 4,
                ballsFaced: 6,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 9,
                runsGiven: 56,
                economy: 6.22,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Naseem Shah',
            teamName: 'Pakistan',
            position: 9,
            stats: {
                role: 'Bowler',
                runsScored: 6,
                ballsFaced: 8,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 8,
                runsGiven: 50,
                economy: 6.25,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Mohammad Wasim',
            teamName: 'Pakistan',
            position: 10,
            stats: {
                role: 'Bowler',
                runsScored: 2,
                ballsFaced: 4,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 7,
                runsGiven: 44,
                economy: 6.29,
                catches: 0
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            scorecardId: 2,
            playerName: 'Usama Mir',
            teamName: 'Pakistan',
            position: 11,
            stats: {
                role: 'Bowler',
                runsScored: 0,
                ballsFaced: 1,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 51,
                economy: 5.1,
                catches: 1
            },
            createdAt: new Date('2024-01-16').toISOString(),
        },

        // Cricket - Scorecard 3 (South Africa vs New Zealand)
        {
            scorecardId: 3,
            playerName: 'Quinton de Kock',
            teamName: 'South Africa',
            position: 1,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 103,
                ballsFaced: 97,
                fours: 11,
                sixes: 3,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 2
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Temba Bavuma',
            teamName: 'South Africa',
            position: 2,
            stats: {
                role: 'Batsman',
                runsScored: 49,
                ballsFaced: 61,
                fours: 5,
                sixes: 0,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Rassie van der Dussen',
            teamName: 'South Africa',
            position: 3,
            stats: {
                role: 'Batsman',
                runsScored: 62,
                ballsFaced: 68,
                fours: 6,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Aiden Markram',
            teamName: 'South Africa',
            position: 4,
            stats: {
                role: 'All-rounder',
                runsScored: 36,
                ballsFaced: 34,
                fours: 3,
                sixes: 1,
                wicketsTaken: 1,
                oversBowled: 6,
                runsGiven: 38,
                economy: 6.33,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'David Miller',
            teamName: 'South Africa',
            position: 5,
            stats: {
                role: 'Batsman',
                runsScored: 42,
                ballsFaced: 31,
                fours: 3,
                sixes: 2,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Heinrich Klaasen',
            teamName: 'South Africa',
            position: 6,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 28,
                ballsFaced: 24,
                fours: 2,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Marco Jansen',
            teamName: 'South Africa',
            position: 7,
            stats: {
                role: 'All-rounder',
                runsScored: 15,
                ballsFaced: 18,
                fours: 1,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 9,
                runsGiven: 44,
                economy: 4.89,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Keshav Maharaj',
            teamName: 'South Africa',
            position: 8,
            stats: {
                role: 'Bowler',
                runsScored: 9,
                ballsFaced: 11,
                fours: 1,
                sixes: 0,
                wicketsTaken: 3,
                oversBowled: 10,
                runsGiven: 41,
                economy: 4.1,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Kagiso Rabada',
            teamName: 'South Africa',
            position: 9,
            stats: {
                role: 'Bowler',
                runsScored: 4,
                ballsFaced: 7,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 49,
                economy: 4.9,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Anrich Nortje',
            teamName: 'South Africa',
            position: 10,
            stats: {
                role: 'Bowler',
                runsScored: 2,
                ballsFaced: 5,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 9,
                runsGiven: 52,
                economy: 5.78,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Lungi Ngidi',
            teamName: 'South Africa',
            position: 11,
            stats: {
                role: 'Bowler',
                runsScored: 0,
                ballsFaced: 2,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 8,
                runsGiven: 46,
                economy: 5.75,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Devon Conway',
            teamName: 'New Zealand',
            position: 1,
            stats: {
                role: 'Wicketkeeper-Batsman',
                runsScored: 78,
                ballsFaced: 86,
                fours: 8,
                sixes: 2,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 2
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Finn Allen',
            teamName: 'New Zealand',
            position: 2,
            stats: {
                role: 'Batsman',
                runsScored: 54,
                ballsFaced: 49,
                fours: 6,
                sixes: 2,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Kane Williamson',
            teamName: 'New Zealand',
            position: 3,
            stats: {
                role: 'Batsman',
                runsScored: 65,
                ballsFaced: 73,
                fours: 6,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Daryl Mitchell',
            teamName: 'New Zealand',
            position: 4,
            stats: {
                role: 'All-rounder',
                runsScored: 41,
                ballsFaced: 38,
                fours: 4,
                sixes: 1,
                wicketsTaken: 1,
                oversBowled: 5,
                runsGiven: 34,
                economy: 6.8,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Glenn Phillips',
            teamName: 'New Zealand',
            position: 5,
            stats: {
                role: 'All-rounder',
                runsScored: 33,
                ballsFaced: 29,
                fours: 3,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 4,
                runsGiven: 31,
                economy: 7.75,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Mark Chapman',
            teamName: 'New Zealand',
            position: 6,
            stats: {
                role: 'Batsman',
                runsScored: 26,
                ballsFaced: 24,
                fours: 2,
                sixes: 1,
                wicketsTaken: 0,
                oversBowled: 0,
                runsGiven: 0,
                economy: 0,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Mitchell Santner',
            teamName: 'New Zealand',
            position: 7,
            stats: {
                role: 'All-rounder',
                runsScored: 18,
                ballsFaced: 16,
                fours: 1,
                sixes: 1,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 47,
                economy: 4.7,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Matt Henry',
            teamName: 'New Zealand',
            position: 8,
            stats: {
                role: 'Bowler',
                runsScored: 7,
                ballsFaced: 9,
                fours: 0,
                sixes: 0,
                wicketsTaken: 3,
                oversBowled: 10,
                runsGiven: 51,
                economy: 5.1,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Trent Boult',
            teamName: 'New Zealand',
            position: 9,
            stats: {
                role: 'Bowler',
                runsScored: 3,
                ballsFaced: 6,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 9,
                runsGiven: 48,
                economy: 5.33,
                catches: 1
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Tim Southee',
            teamName: 'New Zealand',
            position: 10,
            stats: {
                role: 'Bowler',
                runsScored: 1,
                ballsFaced: 3,
                fours: 0,
                sixes: 0,
                wicketsTaken: 1,
                oversBowled: 8,
                runsGiven: 54,
                economy: 6.75,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            scorecardId: 3,
            playerName: 'Lockie Ferguson',
            teamName: 'New Zealand',
            position: 11,
            stats: {
                role: 'Bowler',
                runsScored: 0,
                ballsFaced: 1,
                fours: 0,
                sixes: 0,
                wicketsTaken: 2,
                oversBowled: 10,
                runsGiven: 56,
                economy: 5.6,
                catches: 0
            },
            createdAt: new Date('2024-01-17').toISOString(),
        },

        // F1 - Scorecard 4 (Monaco Grand Prix)
        {
            scorecardId: 4,
            playerName: 'Max Verstappen',
            teamName: 'Red Bull Racing',
            position: 1,
            stats: {
                team: 'Red Bull Racing',
                finishingPosition: 1,
                startPosition: 1,
                time: '1:32:15.456',
                points: 25,
                fastestLap: true,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Charles Leclerc',
            teamName: 'Ferrari',
            position: 2,
            stats: {
                team: 'Ferrari',
                finishingPosition: 2,
                startPosition: 3,
                time: '+2.345',
                points: 18,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Lewis Hamilton',
            teamName: 'Mercedes',
            position: 3,
            stats: {
                team: 'Mercedes',
                finishingPosition: 3,
                startPosition: 2,
                time: '+5.678',
                points: 15,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Sergio Perez',
            teamName: 'Red Bull Racing',
            position: 4,
            stats: {
                team: 'Red Bull Racing',
                finishingPosition: 4,
                startPosition: 5,
                time: '+8.234',
                points: 12,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Fernando Alonso',
            teamName: 'Aston Martin',
            position: 5,
            stats: {
                team: 'Aston Martin',
                finishingPosition: 5,
                startPosition: 4,
                time: '+12.567',
                points: 10,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Carlos Sainz',
            teamName: 'Ferrari',
            position: 6,
            stats: {
                team: 'Ferrari',
                finishingPosition: 6,
                startPosition: 7,
                time: '+15.890',
                points: 8,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'George Russell',
            teamName: 'Mercedes',
            position: 7,
            stats: {
                team: 'Mercedes',
                finishingPosition: 7,
                startPosition: 6,
                time: '+18.345',
                points: 6,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Lando Norris',
            teamName: 'McLaren',
            position: 8,
            stats: {
                team: 'McLaren',
                finishingPosition: 8,
                startPosition: 8,
                time: '+21.678',
                points: 4,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Oscar Piastri',
            teamName: 'McLaren',
            position: 9,
            stats: {
                team: 'McLaren',
                finishingPosition: 9,
                startPosition: 10,
                time: '+24.123',
                points: 2,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Lance Stroll',
            teamName: 'Aston Martin',
            position: 10,
            stats: {
                team: 'Aston Martin',
                finishingPosition: 10,
                startPosition: 9,
                time: '+26.789',
                points: 1,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Pierre Gasly',
            teamName: 'Alpine',
            position: 11,
            stats: {
                team: 'Alpine',
                finishingPosition: 11,
                startPosition: 11,
                time: '+29.456',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Esteban Ocon',
            teamName: 'Alpine',
            position: 12,
            stats: {
                team: 'Alpine',
                finishingPosition: 12,
                startPosition: 12,
                time: '+32.234',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Alexander Albon',
            teamName: 'Williams',
            position: 13,
            stats: {
                team: 'Williams',
                finishingPosition: 13,
                startPosition: 13,
                time: '+35.678',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Logan Sargeant',
            teamName: 'Williams',
            position: 14,
            stats: {
                team: 'Williams',
                finishingPosition: 14,
                startPosition: 15,
                time: '+38.901',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Valtteri Bottas',
            teamName: 'Alfa Romeo',
            position: 15,
            stats: {
                team: 'Alfa Romeo',
                finishingPosition: 15,
                startPosition: 14,
                time: '+41.456',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Zhou Guanyu',
            teamName: 'Alfa Romeo',
            position: 16,
            stats: {
                team: 'Alfa Romeo',
                finishingPosition: 16,
                startPosition: 16,
                time: '+44.789',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Kevin Magnussen',
            teamName: 'Haas',
            position: 17,
            stats: {
                team: 'Haas',
                finishingPosition: 17,
                startPosition: 17,
                time: '+47.234',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Nico Hulkenberg',
            teamName: 'Haas',
            position: 18,
            stats: {
                team: 'Haas',
                finishingPosition: 18,
                startPosition: 18,
                time: '+50.678',
                points: 0,
                fastestLap: false,
                lapsCompleted: 78,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Yuki Tsunoda',
            teamName: 'AlphaTauri',
            position: 19,
            stats: {
                team: 'AlphaTauri',
                finishingPosition: 19,
                startPosition: 19,
                time: 'DNF',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Retirement - Engine'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            scorecardId: 4,
            playerName: 'Daniel Ricciardo',
            teamName: 'AlphaTauri',
            position: 20,
            stats: {
                team: 'AlphaTauri',
                finishingPosition: 20,
                startPosition: 20,
                time: 'DNF',
                points: 0,
                fastestLap: false,
                lapsCompleted: 38,
                status: 'Retirement - Gearbox'
            },
            createdAt: new Date('2024-01-18').toISOString(),
        },

        // F1 - Scorecard 5 (British Grand Prix)
        {
            scorecardId: 5,
            playerName: 'Lewis Hamilton',
            teamName: 'Mercedes',
            position: 1,
            stats: {
                team: 'Mercedes',
                finishingPosition: 1,
                startPosition: 2,
                time: '1:27:45.678',
                points: 26,
                fastestLap: true,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Max Verstappen',
            teamName: 'Red Bull Racing',
            position: 2,
            stats: {
                team: 'Red Bull Racing',
                finishingPosition: 2,
                startPosition: 1,
                time: '+1.234',
                points: 18,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Lando Norris',
            teamName: 'McLaren',
            position: 3,
            stats: {
                team: 'McLaren',
                finishingPosition: 3,
                startPosition: 4,
                time: '+3.567',
                points: 15,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'George Russell',
            teamName: 'Mercedes',
            position: 4,
            stats: {
                team: 'Mercedes',
                finishingPosition: 4,
                startPosition: 3,
                time: '+5.890',
                points: 12,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Charles Leclerc',
            teamName: 'Ferrari',
            position: 5,
            stats: {
                team: 'Ferrari',
                finishingPosition: 5,
                startPosition: 5,
                time: '+8.234',
                points: 10,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Oscar Piastri',
            teamName: 'McLaren',
            position: 6,
            stats: {
                team: 'McLaren',
                finishingPosition: 6,
                startPosition: 7,
                time: '+11.567',
                points: 8,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Sergio Perez',
            teamName: 'Red Bull Racing',
            position: 7,
            stats: {
                team: 'Red Bull Racing',
                finishingPosition: 7,
                startPosition: 6,
                time: '+14.890',
                points: 6,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Fernando Alonso',
            teamName: 'Aston Martin',
            position: 8,
            stats: {
                team: 'Aston Martin',
                finishingPosition: 8,
                startPosition: 8,
                time: '+18.234',
                points: 4,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Carlos Sainz',
            teamName: 'Ferrari',
            position: 9,
            stats: {
                team: 'Ferrari',
                finishingPosition: 9,
                startPosition: 9,
                time: '+21.567',
                points: 2,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Lance Stroll',
            teamName: 'Aston Martin',
            position: 10,
            stats: {
                team: 'Aston Martin',
                finishingPosition: 10,
                startPosition: 10,
                time: '+24.890',
                points: 1,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Alexander Albon',
            teamName: 'Williams',
            position: 11,
            stats: {
                team: 'Williams',
                finishingPosition: 11,
                startPosition: 11,
                time: '+28.234',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Pierre Gasly',
            teamName: 'Alpine',
            position: 12,
            stats: {
                team: 'Alpine',
                finishingPosition: 12,
                startPosition: 12,
                time: '+31.567',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Esteban Ocon',
            teamName: 'Alpine',
            position: 13,
            stats: {
                team: 'Alpine',
                finishingPosition: 13,
                startPosition: 13,
                time: '+34.890',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Valtteri Bottas',
            teamName: 'Alfa Romeo',
            position: 14,
            stats: {
                team: 'Alfa Romeo',
                finishingPosition: 14,
                startPosition: 14,
                time: '+38.234',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Zhou Guanyu',
            teamName: 'Alfa Romeo',
            position: 15,
            stats: {
                team: 'Alfa Romeo',
                finishingPosition: 15,
                startPosition: 15,
                time: '+41.567',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Kevin Magnussen',
            teamName: 'Haas',
            position: 16,
            stats: {
                team: 'Haas',
                finishingPosition: 16,
                startPosition: 16,
                time: '+44.890',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            scorecardId: 5,
            playerName: 'Nico Hulkenberg',
            teamName: 'Haas',
            position: 17,
            stats: {
                team: 'Haas',
                finishingPosition: 17,
                startPosition: 17,
                time: '+48.234',
                points: 0,
                fastestLap: false,
                lapsCompleted: 52,
                status: 'Finished'
            },
            createdAt: new Date('2024-01-19').toISOString(),
        },